services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=loki'
      - 'POSTGRES_PASSWORD=esphero'
      - 'POSTGRES_USER=esphero'
    ports:
      - '5432:5432'
    networks:
      - 'esphero-net'

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    networks:
      - 'esphero-net'

  loki:
    image: 'docker.io/library/loki:0.0.1-SNAPSHOT'
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/loki?ApplicationName=Master'
      - 'SPRING_DATASOURCE_USERNAME=esphero'
      - 'SPRING_DATASOURCE_PASSWORD=esphero'
      - 'SPRING_PROFILES_ACTIVE=dev'
      - 'LOKI_REDIS_HOST=redis'
    depends_on:
      - 'postgres'
      - 'redis'
    networks:
      - 'esphero-net'

networks:
  esphero-net: